module.exports = {
    "case3": "3) ETH price on Jul 6, 0:00 (UTC): 1783.77\nLucky draw no.: 7\nQualified participants: 8,849\nMembers per group: 8,849/2,000\n● 1st 849 groups: 5 people\n● Last 1,151 groups: 4 person each\nWinner:\n● 1st 849 groups: 2nd person of 5 in the group\n● Last 1,151 groups: The 3rd person of 4 in the group",
    "nftwebsite_roadmap.title": "The Moment3!",
    "nftwebsite_team.Cobe": "Cobe",
    "nftwebsite_public.Quantity": "Quantity",
    "nft_whitepaper": "Whitepaper",
    "nft_Connectwallet": "Connect wallet",
    "nftwebsite_benefits.Benefits": "The Moment3!\nBenefits",
    "nft_done": "Thank you for participating",
    "nftwebsite_zhuzao.start": "Jul 6, 2023 15:00 (KST)",
    "app.check": "success",
    "nftwebsite_roadmap.Onlineandopenforsale": "Online and open for sale",
    "nftwebsite_culture.story2": "Every season we will work with our community members to select a theme, then use this theme to work with other projects, communities or companies that share our vision and value.",
    "nftwebsite_public.Unitprice": "Unit price",
    "nftwebsite_introduc.subtitle": "AliExpress X The Moment3! NFT collection",
    "nftwebsite_tasks.Open": "Open the app",
    "nftwebsite_roadmap.quarterstheme": "Based on each quarter's theme, we will cooperate with the top individuals, communities & companies in line with the values of The Moment3!",
    "nftwebsite_shouye.TheMoment3": "The Moment3!",
    "nftwebsite_qualified.qualified1": "You've qualified! Your lucky draw number is",
    "nftwebsite_team.TechCryptoBear": "Tech CryptoBear",
    "nftwebsite_benefits.virtualworlds": "The Moment3! will continue to link up with outstanding organizations, communities or businesses so that owners of our NFTs enjoy a variety of benefits, & perks via airdrops in the real and virtual worlds.",
    "nftwebsite_team.FounderCobe": "Founder Cobe",
    "nftwebsite_zhuzao.end": "Jul 7, 2023 15:00 (KST)",
    "nftwebsite_team.Project": "Project",
    "nftwebsite_Congratulate.lucky": "Congratulations! You're a winner in the lucky draw",
    "nftwebsite_zhuzao.starttime": "Jul 6, 2023 15:00 (KST)\nPrice: Free",
    "nftwebsite_shouye.Benefits": "Benefits",
    "nftwebsite_public.0.088ETH": "0.088ETH ",
    "nftwebsite_shouye.Roadmap": "Roadmap",
    "nftwebsite_team.OperationsMaggieC": "Operations MaggieC",
    "nftwebsite_tasks.status": "Your status",
    "case2": "2) ETH price on Jul 6, 0:00 (UTC): 1783.30\nLucky draw no.: 3\nQualified participants: 3,721\nMembers per group: 3,721/2,000\n● 1st 1,721 groups: 2 people\n● Last 279 groups: 1 person each\nWinner:\n● 1st 1,721 groups: 1st person of 2 in the group\n● Last 279 groups: The 1st member of that group",
    "whitecontent": "Allowlist period: Jun 24, 2023 0:00 - Jul 6, 2023 0:00 (KST)\nComplete all 3 tasks on AliExpress during this period to qualify for the free mint lucky draw:\nTask 1: Follow The Moment3! Twitter account & retweet our post\nTask 2: Complete an order for US $1 or more on AliExpress\nTask 3:  Invite 3 friends to join AliExpress & 1 of them completes an order for US $1 or more on AliExpress\n\nEarly bird special\nEarly supporters who qualify for the allowlist (lucky draw) can mint up to 5 NFTs per person before the public sale. Your free NFTs will be accounted for automatically; you only need to pay for the additional NFTs you mint (a total of 5 max, including both free & purchased NFTs).",
    "nftwebsite_roadmap.Future": "Future",
    "nftwebsite_roadmap.Season1": "The Moment3! Season 1: Buying The Moment3!",
    "nftwebsite_roadmap.Season2": "Season 2",
    "nftwebsite_team.ProjectSilver": "Project Silver",
    "nftwebsite_team.Operations": "Operations",
    "NFTruler": "Minting rules:",
    "nftwebsite_introduc.JoinDiscord": "Join Discord",
    "nftwebsite_free.participating": "Thanks for participating. Stay tuned for the public release.",
    "nftwebsite_zhuzao.free": "Price: Free",
    "nftwebsite_roadmap.Oct": "Oct - Dec 2023",
    "nftwebsite_Congratulate.0.088": "0.088 ETH",
    "nftwebsite_lost.notselected": "Sorry, your number was not selected. You can still take part in the public sale on Jul 7, 2023 15:00 (KST)",
    "nftwebsite_Congratulate.Remaining": "Remaining NFTs: [33}/{5,555}",
    "nft_minted": "{0) NFTs minted. You can still mint up to {1} more.",
    "nftwebsite_team.Artist": "Artist",
    "nftwebsite_tasks.AliExpress": "The Moment3! X AliExpress NFT",
    "nftwebsite_overtime.haventqualified": "While you haven't qualified for the lucky draw, you can still take part in the public sale: Jul 7, 2023 15:00 (KST)",
    "nftwebsite_roadmap.roadmap": "Roadmap",
    "nftwebsite_dibu.Followus": "Follow us",
    "nftwebsite_Congratulate.Total": "Total:",
    "nftwebsite_Congratulate.Amountdue": "Amount due",
    "nftwebsite_Congratulate.mint": "Quantity to mint",
    "nftwebsite_shouye.Vision": "Vision",
    "nftwebsite_team.Teamunitesveterans": "The Moment3! Team unites veterans from diverse industries and backgrounds who have a track record of success. With our combined talents, we'll be bringing our NFT owners a host of benefits.",
    "nftwebsite_tasks.winners1": "Number of winners:",
    "nftwebsite_lost.Winnerslist": "Winners list",
    "nftwebsite_benefits.enjoy": "Own a The Moment3! NFT and enjoy a range of benefits",
    "nftwebsite_lost.Won": "Won",
    "nftwebsite_lost.not": "Sorry, your number was not selected. ",
    "nft_Learnmore": "Learn more",
    "nftwebsite_qualified.qualified": "You've qualified! Your lucky draw number is {#0001}",
    "nftwebsite_overtime.havent1": "You can still take part in the public sale: Jul 7, 2023 15:00 (KST)",
    "nftwebsite_tasks.Complete": "Join the NFT revolution and own a piece of the hype",
    "nftwebsite_dibu.2023": "The Moment3! 2023",
    "nftwebsite_shouye.Partners": "Partners",
    "nftwebsite_public.Total": "Total {3,555}",
    "nftwebsite_Congratulate.Winnerslist": "Winners list",
    "nftwebsite_tasks.Complete1": "Complete tasks on our app",
    "nftwebsite_lost.not1": "You can still take part in the public sale on Jul 7, 2023 15:00 (KST)",
    "nftwebsite_roadmap.Jul": "Jul - Sep 2023",
    "nftwebsite_shouye.Theteam": "The team",
    "nftwebsite_fubiaoti.5555unique": "5,555 unique The Moment3! NFTs. Celebrate each precious moment.",
    "nftwebsite_tasks.winners": "Number of winners: 2,000",
    "nftwebsite_zhuzao.endtime": "Jul 7, 2023 15:00 (KST)\nPrice: 0.088 ETH",
    "nftwebsite_culture.Vision": "Vision",
    "nftwebsite_partner.Partners": "Partners",
    "nftwebsite_team.TheMoment3": "The Moment3!",
    "nftwebsite_zhuzao.0088": "Price: 0.088 ETH",
    "nftwebsite_roadmap.Benefits": "The Moment 3! Benefits & airdropping launch ",
    "nftwebsite_roadmap.Apr": "Apr - Jun 2023",
    "nftwebsite_public.{1}": "{1}",
    "nftwebsite_zhuzao.Publicmint": "Public mint",
    "nftwebsite_Congratulate.0.00ETH": "0.00 ETH",
    "nftwebsite_roadmap.Collaborations": "Collaborations with various brands",
    "nftwebsite_Congratulate.0.088ETH": "0.088 ETH",
    "nftwebsite_tasks.number": "Get your free mint lucky draw number",
    "nftwebsite_Congratulate.UNITS": "-{UNITS*0.088} ETH ({1} free)",
    "nftwebsite_zhuzao.Freemint": "Free mint",
    "nftwebsite_public.Remaining1": "Remaining NFTs: {0}",
    "nftwebsite_free.Jul7": "Jul 7, 2023 15:00 (KST)",
    "nftwebsite_culture.story": "3. The choices you make in every moment add up to you, and that's why every moment is so precious and special. Meet The Moment3! NFT, which captures all the eternal moments in your chain.\nEvery season we will work with our community members to select a theme, then use this theme to work with other projects, communities or companies that share our vision and value.\n",
    "nftwebsite_Congratulate.Mintnow": "Mint now",
    "nftwebsite_overtime.havent": "While you haven't qualified for the lucky draw.",
    "nftwebsite_roadmap.quarterlyroll": "Stay tuned for our quarterly roll out of new benefits for owners of The Moment 3! NFTs. Together we'll build a better community.",
    "nftwebsite_public.title": "The Moment3!",
    "nftwebsite_culture.story1": "The choices you make in every moment add up to you, and that's why every moment is so precious and special. Meet The Moment3! NFT, which captures all the eternal moments in your chain.",
    "nftwebsite_introduc.learnmore": "Learn more",
    "nftwebsite_Congratulate.5NFTs": "Early qualifiers can mint up to 5 NFTs. You can mint up to {1} NFTs for free. ",
    "nftwebsite_lost.Lost": "Lost ",
    "nftwebsite_team.MaggieC": "MaggieC",
    "nftwebsite_tasks.allowlist": "Get added to the allowlist",
    "nftwebsite_team.Pallas": "Pallas",
    "nft_soldout": "Sold out",
    "nftwebsite_team.Founder": "Founder",
    "nftwebsite_Congratulate.Discount": "Discount:",
    "nftwebsite_team.Theteam": "The team",
    "whitetuler": "How to qualify for the allowlist lucky draw",
    "nftwebsite_introduc.TheMoment3": "The Moment3!",
    "nftwebsite_Congratulate.Unitprice": "Unit price:",
    "nftwebsite_team.CryptoBear": "CryptoBear",
    "rulercontent": "1. Total supply: 5,555\n2. Minting schedule:\nAllowlist pre-sale: Jul 6, 2023 15:00 (KST)\nPublic sale: Jul 7, 2023 15:00 (KST)\n3. Allowlist pre-sale quantity: approx. 2,000\n4. Public sale quantity: approx. 3,555, price: 0.0088 ETH/per NFT, max. 5 NFT/per person",
    "nftwebsite_culture.subtitle": "Every Moment is irreplaceable!",
    "nftwebsite_partner.MeettheTeamBehindTheMoment3": "Meet the team behind The Moment3!",
    "nftwebsite_Congratulate.Remaining1": "Remaining NFTs: {0}/{1}",
    "case1": "Examples\n1) ETH price on Jul 6, 0:00 (UTC): 1783.81\nLucky draw no.: 1\nQualified participants: 4,000\nMembers per group: 4,000/2,000 = 2\nWinner: 1st person of 2 in each group",
    "nftwebsite_dibu.metaverse": "NFT metaverse by The Moment3!",
    "nftwebsite_tasks.Step1": "Step 1",
    "nftwebsite_Congratulate.Limit": "Limit: 5 NFTs per person",
    "nftwebsite_tasks.Step2": "Step 2",
    "nftwebsite_team.Silver": "Silver",
    "nftwebsite_team.Tech": "Tech",
    "nftwebsite_public.Remaining": "Remaining NFTs: [33}",
    "nftwebsite_roadmap.Communitymembers": "Community members vote to select the theme",
    "nftwebsite_Congratulate.UNITS1": "-{0} ETH ({1} free)",
    "nftwebsite_tasks.Jul6": "Jul 6, 2023 15:00 (KST) ",
    "nftwebsite_public.5person": "Limit: 5 NFTs per person",
    "nftwebsite_tasks.Time": "Time ",
    "nftwebsite_overtime.Sorry": "Sorry, you didn't complete the missions on time.",
    "nftwebsite_tasks.Eligible": "Eligible for draw",
    "whiteprovide": "Allowlist rules:",
    "nftwebsite_roadmap.announceadditionalbenefits": "The Moment3! will announce additional benefits from AliExpress and our partners & enable airdropping ",
    "nftwebsite_free.participate": "Thanks for participating. ",
    "nftwebsite_public.Mintnow": "Mint now",
    "nftwebsite_introduc.time": "AliExpress X The Moment3! will release a total of 5,555 NFTs on Jun 25, 2023 (KST). Come discover the handsome design featuring Korea's national treasure, the Jindo-gae, as the theme of the 1st season!",
    "nftwebsite_tasks.Lucky": "Lucky draw to free mint",
    "nftwebsite_zhuzao.Mintnow": "Mint now",
    "endclause": "The lucky draw results will be announced on the official website, Twitter, and Discord. The Moment3! holds all rights to the final interpretation of the event and lucky draw results.",
    "nftwebsite_zhubiaoti.DiscoverTheMoment3NFTcollection": "Discover The Moment3!\nNFT collection ",
    "nftwebsite_public.Publicminting": "Public minting",
    "nftwebsite_team.ArtistPallas": "Artist Pallas",
    "providecontent": "1. If 2,000 participants or less qualify by completing all missions, then all participants will be automatically added to the allowlist.\n2. If more than 2,000 participants qualify, we will hold an allowlist lucky draw. \n  ○ The number of participants per group is equal to the total number of qualified divided by 2,000.\nIf there is a remainder, those participants will be equaly divided among the groups.\nExample: If there are 7,549 qualified, then all groups will have at least 3 members + the first 1,549 groups will have 4 members (7,539/2,000 = 3 remainder 1,549)\n  ○ The lucky draw will use the last non-zero digit of the Ethereum to US dollar exchange rate on the Binance Exchange on Jul 6, 2023 0:00 (UTC)."
};