module.exports = {
    "nftwebsite_culture.Vision": "일사분기",
    "nftwebsite_tasks.winners": "추첨 수량: 2,000",
    "nftwebsite_zhuzao.0088": "가격: 0.088 ETH",
    "nftwebsite_roadmap.47": "2023년 4월~7월",
    "nftwebsite_schedule_free": "얼라우리스트 프리 세일: 2023년 7월 6일 15:00(한국시간) ",
    "nftwebsite_rules.task.3": "미션 3: AliExpress 앱에 가입한 친구 3명 중 1명이 US $1 이상의 주문을 완료하게 도와주세요",
    "nftwebsite_public.5person": "1인당 최대 5개",
    "nftwebsite_Congratulate.Remaining1": "잔여 수량: {0}/{1}",
    "nftwebsite_thankyou": "참여해 주셔서 감사합니다",
    "nftwebsite_roadmap.Oct": "2023년 10월 - 12월",
    "nftwebsite_Congratulate.0.00ETH": "0.00 ETH",
    "nftwebsite_lost.notselected": "아쉽게도 이벤트에 당첨되지 않으셨습니다. 퍼블릭 세일을 기대해 주세요. \n퍼블릭 세일 시간: 2023년 7월 7일 15:00(한국시간) ",
    "nftwebsite_end_content": "추첨 결과는 공식 웹사이트, 트위터, Discord에서 공개됩니다. The Moment3!에서 이벤트 및 추첨 결과의 최종 해석에 대한 모든 권리를 보유합니다.",
    "nftwebsite_rules.allowlist.rules": "얼라우리스트 선정 방법",
    "nftwebsite_partner.holder": "The Moment3!는 파트너사와 협력하여 NFT 홀더에게 서비스를 제공합니다.",
    "nftwebsite_team.TheMoment3": "The Moment3!",
    "nftwebsite_mint_rules_title": "NFT 발행 룰:",
    "nftwebsite_roadmap.Communitymembers": "커뮤니티 투표를 통해 시즌 2 주제 선정",
    "nftwebsite_roadmap.Jul": "2023년 7월 - 9월",
    "nftwebsite_public.{1}": "{1}",
    "nftwebsite_zhuzao.endtime": "2023년 7월 7일 15:00(한국시간)\n가격: 0.088 ETH",
    "nftwebsite_zhuzao.start": "2023년 7월 6일 15:00(한국시간)",
    "nftwebsite_roadmap.Benefitsairdropping": "베네핏 & 에어드랍 시작",
    "nft_soldout": "매진",
    "nftwebsite_team.CryptoBear": "CryptoBear",
    "nftwebsite_team.MaggieC": "MaggieC",
    "nftwebsite_team.Pallas": "Pallas",
    "nftwebsite_open.notqualified": "미션 미완성",
    "nftwebsite_overtime.havent1": "퍼블릭 세일 시간: 2023년 7월 7일 15:00(한국시간)",
    "nftwebsite_roadmap.quarterstheme": "분기별 테마를 기반으로 가장 관련성이 높은 개인, 커뮤니티, 기업과 협력하여 NFT 홀더에게 서비스 제공",
    "nftwebsite_number.close": "닫기",
    "nftwebsite_public.Remaining1": "잔여 수량: {0}개",
    "rulercontent": "1: 총 NFT 갯수: 5555개\n2: 판매 방식: \n얼라우리스트 프리 세일: 2023년 7월 6일 15:00(한국시간)\n퍼블릭 세일: 2023년 7월 7일 15:00(한국시간)\n3: 얼라우리스트 프리 세일: 약 2,000개\n4: 퍼블릭 세일: 약 3,555개, 0.088 ETH/개, 인당 최대 5개 민팅 가능",
    "nftwebsite_open.only0": "{0}개 남음",
    "nftwebsite_Congratulate.UNITS": "-{UNITS*0.088} ETH (NFT {1}개 무료)",
    "nftwebsite_zhuzao.Freemint": "프리 민팅",
    "whitetuler": "얼라우리스트 추첨 신청 조건:",
    "nftwebsite_rules.75": "2023년 7월 6일 15:00(한국시간)",
    "nftwebsite_rules.allowlist": "얼라우리스트 프리 세일: ",
    "nftwebsite_Congratulate.Discount": "할인:",
    "nftwebsite_rules.mintingschedule": "판매 방식",
    "nftwebsite_tasks.number": "무료 민팅 추첨 번호를 받으세요",
    "nftwebsite_roadmap.Onlineandopenforsale": " [The Moment3! X AliExpress] 온라인 출시 & 얼라우리스트 응모 개시",
    "nftwebsite_team.Cobe": "Cobe",
    "nftwebsite_roadmap.Collaborations": "다양한 브랜드 컬래버레이션",
    "nftwebsite_rules.task.2": "미션 2: AliExpress에서 US $1 이상의 상품을 주문해 주세요",
    "nftwebsite_dibu.Followus": "SNS 계정 팔로우",
    "nftwebsite_schedule_title": "2: 판매 방식: ",
    "nftwebsite_team.Founder": "파운더",
    "nftwebsite_Congratulate.Amountdue": "총 결제금액",
    "nftwebsite_allowlist_title": "얼라우리스트 선정 방법:",
    "nftwebsite_zhu_freeend": "프리 민팅 종료",
    "nft_home_qualified": "참가인원 {0}명",
    "nftwebsite_public.title": "The Moment3!",
    "nftwebsite_overtime.havent": "무료 민팅 자격을 얻지 못했습니다. 퍼블릭 세일을 기대해 주세요. ",
    "nftwebsite_tasks.Complete": "한정판 NFT 증정 이벤트에 참여하세요",
    "nftwebsite_team.Teamunitesveterans": "저희 The Moment3!는 다양한 배경에서 수많은 경험에 도전해 본 여러 분야의 베테랑들이 모여 하나의 목소리를 내는 팀입니다. 책임감과 사명을 가지고 새로운 에픽, The Moment3! NFT를 이뤄내겠습니다. ",
    "nftwebsite_free.Jul7": "2023년 7월 7일 15:00(한국시간)",
    "nftwebsite_Congratulate.5NFTs": "{0} 개 무료 획득.",
    "nftwebsite_team.FounderCobe": "파운더 Cobe",
    "nftwebsite_lost.Won": "당첨",
    "nftwebsite_culture.story": "모든 순간의 선택이 모여 \"내\"가 됩니다. 그렇기에 모든 순간은 무엇과도 바꿀 수 없는 소중하고 특별한 것입니다. 체인 속 영원히 변함없는 모든 순간을 담은 The Moment3! NFT를 만나보세요. \nThe Moment3!는 커뮤니티와 함께 테마를 선정하고, 같은 비전을 공유하는 더 큰 프로젝트, 단체 및 기업과 협업하여 유니크한 컬렉션을 선보일 예정입니다.",
    "nftwebsite_lost.Winnerslist": "당첨자 명단",
    "nftwebsite_rules.allowlist.rules1": "1. 참가 인원이 4,500명 미만인 경우, 모든 참가자가 얼라우리스트로 선정됩니다.",
    "nftwebsite_zhuzao.free": "가격: 무료",
    "NFTruler": "NFT 발행 룰:",
    "nftwebsite_tasks.Step2": "Step 2",
    "nftwebsite_shouye.Partners": "파트너사",
    "nftwebsite_Congratulate.UNITS1": "-{0} ETH (NFT {1}개 무료)",
    "nft_minted": "{0}개 민팅완료. {1}개 추가 가능.",
    "nft_whitepaper": "백서",
    "nftwebsite_tasks.Step1": "Step 1",
    "nftwebsite_tasks.Jul6": "2023년 7월 6일 15:00(한국시간)",
    "nftwebsite_tasks.status": "상태",
    "nftwebsite_early_bird_special_title": "얼리버드 혜택: ",
    "nftwebsite_rules.minting": "NFT 발행 룰",
    "case1": "예1) \n이더리움 가격: $1783.81\n그룹 내 추첨 순번: 1\n참가 인원: 4000명\n그룹 인원: 4000명을 2000개의 그룹으로 나누어 각 그룹에 2명이 배정됩니다\n당첨 결과: 추첨 순번에 따라 각 그룹 내 1번째 참가자가 당첨됩니다(추첨 번호 1, 3, 5, 7, 9...3999)",
    "nftwebsite_team.AIArtist": "AI 아티스트",
    "nftwebsite_roadmap.Future": "향후계획",
    "nftwebsite_qualify": "얼라우리스트 추첨 신청 조건:",
    "nftwebsite_roadmap.roadmap": "로드맵",
    "nftwebsite_overtime.haventqualified": "무료 민팅 자격을 얻지 못했습니다. 퍼블릭 세일을 기대해 주세요. \n퍼블릭 세일 시간: 2023년 7월 7일 15:00(한국시간)",
    "nftwebsite_tasks.AliExpress": "The Moment3! X AliExpress 무료 NFT",
    "nftwebsite_team.Artist": "아티스트",
    "nftwebsite_tase2": "미션 2: AliExpress에서 US $1 이상의 상품을 주문해 주세요",
    "nftwebsite_team.TechCryptoBear": "엔지니어 CryptoBear",
    "nftwebsite_open.gonow": "바로가기",
    "nftwebsite_shouye.TheMoment3": "The Moment3!",
    "nftwebsite_zhubiaoti.DiscoverTheMoment3NFTcollection": "The Moment3! NFT 컬렉션을 만나보세요",
    "nftwebsite_rules.howtoqualify": "얼라우리스트 추첨 신청 조건",
    "nftwebsite_free.participate": "참여해 주셔서 감사합니다",
    "providecontent": "1. 참가 인원이 2,000명 미만인 경우, 모든 참가자가 얼라우리스트로 선정됩니다.\n2. 참가 인원이 2,000명을 초과한 경우, 추첨이 진행됩니다. 2023년 7월 6일 00:00(한국시간) 기준 바이낸스 거래소 이더리움 가격의 0을 제외한 마지막 자리 숫자가 그룹 내 추첨 순번이 되며 전체 참가자는 2000개의 그룹으로 나누어집니다(2000개로 나눈 후 맞아 떨어지지 않은 나머지 참가 인원은 첫 번째 그룹부터 한명씩 추가 배정됩니다). 그 후 각 그룹의 첫 번째 인원부터 차례대로 돌아가며 순서를 매겨 추첨 순번에 해당하는 참가자가 얼라우리스트로 선정됩니다. 아래의 추가 예시를 참고해 주세요.",
    "nftwebsite_zhuzao.Mintnow": "지금 민팅하기",
    "nftwebsite_benefits.virtualworlds": "The Moment3! NFT 보유 시 현실 세계 및 가상 세계 에어드랍을 통해 다양한 혜택을 누릴 수 있도록 단체, 커뮤니티, 기업과 협력하겠습니다.",
    "nftwebsite_introduc.time": "The Moment3! X AliExpress 는 총 5,555개의 NFT 컬렉션을 2023년 6월 25일(한국시간) 정식 출시할 예정입니다. 이번 NFT 테마는 한국의 천연기념물 진돗개입니다. 진돗개의 용맹하고 멋진 이미지를 담은 첫 NFT 컬렉션을 주목해 주세요!",
    "nftwebsite_Congratulate.lucky": "당첨을 축하합니다!",
    "nftwebsite_homepage_freemint_start_time": "2023년 7월 13일 15:00(한국시간)",
    "nftwebsite_zhuzao.end": "2023년 7월 7일 15:00(한국시간)",
    "nftwebsite_overtime.Sorry": "기간 내에 미션을 완료하지 못했습니다.",
    "nftwebsite_limit.5nfts": "1인당 최대 5개 민팅 가능",
    "nftwebsite_allowlist_content": "1. 참가 인원이 2,000명 미만인 경우, 모든 참가자가 얼라우리스트로 선정됩니다.\n2. 참가 인원이 2,000명을 초과한 경우, 추첨이 진행됩니다. 2023년 7월 6일 00:00(한국시간) 기준 바이낸스 거래소 이더리움 가격의 0을 제외한 마지막 자리 숫자가 그룹 내 추첨 순번이 되며 전체 참가자는 2000개의 그룹으로 나누어집니다(2000개로 나눈 후 맞아 떨어지지 않은 나머지 참가 인원은 첫 번째 그룹부터 한명씩 추가 배정됩니다). 그 후 각 그룹의 첫 번째 인원부터 차례대로 돌아가며 순서를 매겨 추첨 순번에 해당하는 참가자가 얼라우리스트로 선정됩니다. 아래의 추가 예시를 참고해 주세요.\n",
    "nftwebsite_tase1": "미션 1: The Moment3! 트위터 계정을 팔로우 & 포스트를 리트윗해 주세요",
    "nftwebsite_public_sale": "4: 퍼블릭 세일: 약 3,555개, 0.088ETH/개, 인당 최대 5개 민팅 가능",
    "nftwebsite_culture.subtitle": "Every Moment is Non-fungible!",
    "nftwebsite_benefits.enjoy": "The Moment3! NFT와 함께 다양한 베네핏을 누려보세요",
    "nftwebsite_roadmap.812": "2023년 8월~12월",
    "nftwebsite_tasks.Eligible": "추첨 대기 중",
    "nftwebsite_qualify_date": "미션 기간: 2023년 6월 24일 00:00(한국시간) ~ 2023년 7월 6일 00:00(한국시간)\n\n이 기간 내에 AliExpress에서 The Moment3! 미션을 모두 완료하면 무료 민팅 얼라우리스트 추첨 기회를 얻을 수 있습니다.",
    "whiteprovide": "얼라우리스트 선정 방법:",
    "nftwebsite_public.Unitprice": "NFT 가격",
    "nftwebsite_shouye.Roadmap": "로드맵",
    "nftwebsite_introduc": "The Moment3! X AliExpress 는 총 5,555개의 NFT 컬렉션을 2023년 6월 25일(한국시간) 정식 출시할 예정입니다. 이번 NFT의 테마는 진돗개입니다. 진돗개의 용맹하고 멋진 이미지를 담은 첫 NFT 컬렉션을 주목해 주세요!",
    "endclause": "추첨 결과는 공식 웹사이트, 트위터, Discord에서 공개됩니다. The Moment3!에서 이벤트 및 추첨 결과의 최종 해석에 대한 모든 권리를 보유합니다.",
    "nftwebsite_rules.total5555": "총 NFT 갯수",
    "nftwebsite_total": "1: 총 NFT 갯수: 5555개",
    "nftwebsite_rules.task.1": "미션 1: The Moment3! 트위터 계정을 팔로우 & 포스트를 리트윗해 주세요 ",
    "nftwebsite_benefits.Benefits": "베네핏",
    "nftwebsite_team.Silver": "Silver",
    "nftwebsite_roadmap.Apr": "2023년 4월 - 6월",
    "nftwebsite_roadmap.Benefits": "The Moment3! 베네핏 & 에어드랍 시작",
    "nftwebsite_public.Quantity": "NFT 수량",
    "nftwebsite_introduc.TheMoment3": "The Moment3!",
    "nftwebsite_public.Remaining": "잔여 수량: {1166}개",
    "nftwebsite_zhu_75": "2023년 7월 6일 15:00(한국시간)",
    "nft_Connectwallet": "지갑 연동하기",
    "nft_done": "참여해 주셔서 감사합니다",
    "nftwebsite_tasks.allowlist": "얼라우리스트 응모하기",
    "nftwebsite_lost.Lost": "미당첨",
    "case3": "예3) \n이더리움 가격: $1783.77\n그룹 내 추첨 순번: 7\n참가 인원: 8849명\n그룹 인원: 8849명을 2000개의 그룹으로 나누어 1~849번째 그룹은 5명, 850~2000번째 그룹은 4명 배정\n당첨 결과: 1번째 인원부터 돌아가면서 순서를 매겨 7번째 순서에 해당하는 인원이 당첨되므로, 1~849번째 그룹은 2번째 인원이 당첨, 850~2000번째 그룹은 3번째 인원이 당첨",
    "nftwebsite_tasks.Time": "시간",
    "nftwebsite_zhuzao.Publicmint": "퍼블릭 민팅",
    "nftwebsite_introduc.JoinDiscord": "Discord 조인하기",
    "nftwebsite_Congratulate.Limit": "1인당 최대 5개",
    "nftwebsite_dibu.metaverse": "NeuralNetics PTE. LTD. NFT 메타버스",
    "nftwebsite_roadmap.title": "The Moment3!",
    "nftwebsite_Congratulate.0.088ETH": "0.088 ETH",
    "nftwebsite_rules.allowlist.rules2": "2. 참가 인원이 4,500명을 초과한 경우, 셔플 알고리즘을 통해 추첨이 진행됩니다. 랜덤 셔플의 시드(seed) 번호는 7월 13일 01:00(한국시간) 기준 이더리움 가격의 마지막 두자리이며, 셔플 후 1~4500번째 인원이 당첨자가 됩니다.",
    "nftwebsite_roadmap.Season.2": "2024년",
    "nftwebsite_tasks.Lucky": "무료 민팅 추첨",
    "nftwebsite_qualified.qualified1": "미션 클리어! 추첨 번호:",
    "nftwebsite_team.ArtistPallas": "아티스트 Pallas",
    "nftwebsite_zhuzao.starttime": "2023년 7월 6일 15:00(한국시간)\n가격: 무료",
    "nftwebsite_partner.MeettheTeamBehindTheMoment3": "함께 The Moment3!를 만들어갈 파트너사를 소개합니다",
    "nftwebsite_culture.story2": "The Moment3!는 커뮤니티와 함께 테마를 선정하고, 같은 비전을 공유하는 더 큰 프로젝트, 단체 및 기업과 협업하여 유니크한 컬렉션을 선보일 예정입니다.",
    "nftwebsite_shouye.Benefits": "베네핏",
    "nftwebsite_team.Project": "프로덕션",
    "nftwebsite_partner.Partners": "파트너사",
    "nftwebsite_pre_sale": "3: 얼라우리스트 프리 세일: 약 2,000개 ",
    "app.check": "success",
    "nftwebsite_introduc.subtitle": "The Moment3! X AliExpress NFT 컬렉션",
    "nftwebsite_open.total0": "총 {0}개",
    "nftwebsite_tasks.Open": "지금 참여하기",
    "nftwebsite_Comingsoon": "곧 시작될 예정입니다",
    "nftwebsite_public.Mintnow": "민팅하기",
    "nftwebsite_rules.complete3tasks": "이 기간 내에 AliExpress에서 The Moment3! 미션을 모두 완료하면 무료 민팅 얼라우리스트 추첨 기회를 얻을 수 있습니다:",
    "nftwebsite_Congratulate.Winnerslist": "당첨자 명단",
    "nftwebsite_free.participating": "참여해 주셔서 감사합니다! 퍼블릭 세일을 기대해 주세요.",
    "nftwebsite_team.ProjectSilver": "프로덕션 Silver",
    "nftwebsite_team.Operations": "오퍼레이션",
    "nftwebsite_public.0.088ETH": "0.088 ETH",
    "nftwebsite_zhu_76": "2023년 7월 7일 15:00(한국시간)",
    "nftwebsite_team.Tech": "엔지니어",
    "nftwebsite_Congratulate.0.088": "0.088 ETH",
    "nftwebsite_roadmap.Season2": "시즌 2: 주제 선정",
    "nftwebsite_Congratulate.Remaining": "잔여 수량: {33}/{4000}",
    "nftwebsite_tasks.Complete1": "AliExpress 앱 미션을 완성하세요",
    "nftwebsite_roadmap.Season1": "시즌 1: 쇼핑 모먼트",
    "nftwebsite_rules.taskperiod": "미션 기간: 2023년 6월 25일 01:00(한국시간) ~ 2023년 7월 13일 01:00(한국시간) ",
    "nftwebsite_team.OperationsMaggieC": "오퍼레이션 MaggieC",
    "nftwebsite_homepage_freemint_end_time": "2023년 7월 14일 15:00(한국시간)",
    "nftwebsite_lost.not1": "퍼블릭 세일 시간: 2023년 7월 7일 15:00(한국시간) ",
    "nftwebsite_roadmap.announceadditionalbenefits": "파트너사의 추가 베네핏 공개 & 에어드랍 시작.",
    "nftwebsite_shouye.Theteam": "팀소개",
    "nftwebsite_fubiaoti.5555unique": "5,555개의 유니크한 The Moment3! NFT로\n소중한 순간을 기념해 보세요",
    "case2": "예2) \n이더리움 가격: $1783.30\n그룹 내 추첨 순번: 3\n참가 인원: 3721명\n그룹 인원: 3721명을 2000개의 그룹으로 나누어 1~1721번째 그룹은 2명, 1722~2000번째 그룹은 1명이 배정\n당첨 결과: 1~1721번째 그룹은 1번째 인원부터 돌아가면서 순서를 매겨 3번째 순서에 해당하는 1번째 인원이 당첨, 1722~2000번째 그룹은 1명이 있으므로 해당 인원이 당첨",
    "whitecontent": "미션 기간: 2023년 6월 24일 00:00(한국시간) ~ 2023년 7월 6일 00:00(한국시간)\n이 기간 내에 AliExpress에서 The Moment3! 미션을 모두 완료하면 무료 민팅 얼라우리스트 추첨 기회를 얻을 수 있습니다.\n미션 1: The Moment3! 트위터 계정을 팔로우 & 포스트를 리트윗해 주세요\n미션 2: AliExpress에서 US $1 이상의 상품을 주문해 주세요\n미션 3: AliExpress 앱에 가입한 친구 3명 중 1명이 US $1 이상의 주문을 완료하게 도와주세요\n\n얼리버드 혜택: \n얼라우리스트 추첨에 당첨된 참가자에게는 얼리버드 혜택이 주어집니다. 퍼블릭 민팅 시작 전에 NFT를 미리 민팅할 수 있으며, 획득한 무료 민팅 NFT 갯수만큼 할인 금액이 적용되어 자동 차감됩니다(최대 5개까지 민팅이 가능하며, 얼라우리스트 민팅은 1인당 1회만 가능합니다).\n",
    "nftwebsite_qualified.qualified": "미션 클리어! 추첨 번호: {#0001}",
    "nftwebsite_culture.story1": "모든 순간의 선택이 모여 \"내\"가 됩니다. 그렇기에 모든 순간은 무엇과도 바꿀 수 없는 소중하고 특별한 것입니다. 체인 속 영원히 변함없는 모든 순간을 담은 The Moment3! NFT를 만나보세요. ",
    "nftwebsite_early_bird_special_content": "얼라우리스트 추첨에 당첨된 참가자에게는 얼리버드 혜택이 주어집니다. 퍼블릭 민팅 시작 전에 NFT를 미리 민팅할 수 있으며, 획득한 무료 민팅 NFT 갯수만큼 할인 금액이 적용되어 자동 차감됩니다(최대 5개까지 민팅이 가능하며, 얼라우리스트 민팅은 1인당 1회만 가능합니다).",
    "nftwebsite_shouye.Vision": "일사분기",
    "nftwebsite_tasks.winners1": "추첨 수량:",
    "nftwebsite_introduc.learnmore": "지금 알아보기",
    "nft_Learnmore": "지금 알아보기",
    "nftwebsite_lost.not": "아쉽게도 이벤트에 당첨되지 않으셨습니다. 퍼블릭 세일을 기대해 주세요.",
    "nftwebsite_roadmap.Season.1": "시즌 1: 쇼핑 모먼트",
    "nftwebsite_team.Theteam": "팀 소개",
    "nftwebsite_dibu.2023": "NeuralNetics PTE. LTD. 2023 ",
    "nftwebsite_zhu_freemint": "프리 민팅 시작",
    "nftwebsite_public.Total": "총 {3,555}개",
    "nftwebsite_Congratulate.Unitprice": "NFT 가격:",
    "nftwebsite_open.75": "2023년 7월 13일 13:00(한국시간)",
    "nftwebsite_Congratulate.Total": "합계:",
    "nftwebsite_schedule_public": "퍼블릭 세일: 2023년 7월 7일 15:00(한국시간)",
    "nftwebsite_Congratulate.Mintnow": "민팅하기",
    "nftwebsite_Congratulate.mint": "NFT 수량",
    "nftwebsite_tase3": "미션 3: AliExpress 앱에 가입한 친구 3명 중 1명이 US $1 이상의 주문을 완료하게 도와주세요",
    "nftwebsite_public.Publicminting": "퍼블릭 민팅",
    "nftwebsite_roadmap.quarterlyroll": "The Moment3!의 분기별 계획 및 방향을 공개합니다. 앞으로 단계적으로 선보일 다양한 베네핏을 기대해 주세요. 여러분과 함께 더 나은 커뮤니티를 만들어가길 기대합니다."
};